name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: HelloWorldTest
      id: helloworldtest
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: HelloWorldTest
        setup-command: mvn compile
        command: Java Hello
        input: ''
        expected-output: '"Hello,World!"'
        comparison-method: exact
        timeout: 2
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        HELLOWORLDTEST_RESULTS: "${{steps.helloworldtest.outputs.result}}"
      with:
        runners: helloworldtest
